### ISSUE TITLE
Cannot find module graphql

### ISSUE THREAD

**Issue by Luciano-Ferreira** [Luciano-Ferreira/Ignite-lab-01-gateway#1]
Error: Cannot find module 'graphql'
Require stack:
- /home/usr/lab-01/gateway/node_modules/@apollo/gateway/dist/index.js
- /home/usr/lab-01/gateway/dist/app.module.js
- /home/usr/lab-01/gateway/dist/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/luciano/2k22/lab-01/gateway/node_modules/@apollo/gateway/src/index.ts:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)

---

**Comment by Luciano-Ferreira** [comment]
Solved. Add graphql and make downgrade graphql@15 in purchases
